### ISSUE TITLE
[TODO] Grados máximos y mínimos con Superíndice y Subíndice

### ISSUE THREAD

**Issue by ruvelro** [edkalrio/batbelt#1]
Configurar Batbelt para que las temperaturas máximas y mínimas aparezcan con superíndice y subíndice.

**Comment by edkalrio** [comment]
Take a look at commit [c01328c4f9e793fbb17051cf56bf90dfffb59503](https://github.com/edkalrio/batbelt/commit/c01328c4f9e793fbb17051cf56bf90dfffb59503)
